# Generated by Django 3.1.7 on 2021-05-19 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('order_id', models.CharField(max_length=25)),
                ('payment_id', models.CharField(max_length=25)),
                ('sign', models.CharField(max_length=100)),
                ('pay_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
