# Generated by Django 3.1.7 on 2021-05-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20210504_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='orderid',
        ),
    ]
