# Generated by Django 3.1.7 on 2021-05-15 16:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status1',
            field=models.CharField(choices=[('NA', '--Not-Available--'), ('Ordered', 'Ordered'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delievered', 'Delievered'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status2',
            field=models.CharField(choices=[('NA', '--Not-Available--'), ('Ordered', 'Ordered'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delievered', 'Delievered'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status3',
            field=models.CharField(choices=[('NA', '--Not-Available--'), ('Ordered', 'Ordered'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delievered', 'Delievered'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status4',
            field=models.CharField(choices=[('NA', '--Not-Available--'), ('Ordered', 'Ordered'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delievered', 'Delievered'), ('Cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2, validators=[django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('All', 'All Season'), ('Spring', 'Spring 1 March'), ('Summer', 'Summer 1 June'), ('Autumn', 'Autumn 1 September'), ('Winter', 'Winter 1 December')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Electronics', (('Washing Machine', 'Washing Machine'), ('Refrigerators', 'Refrigerators'), ('Mixer Grinder & Juicer', 'Mixer Grinder & Juicer'), ('Others', 'Others'))), ('TV & Appliances', (('LCD', 'LCD TV'), ('LED', 'LED TV'), ('LEDSmart', 'LED Smart TV'), ('Others', 'Others'))), ('Men', (('Jeans', 'Jeans'), ('Trousers', 'Trousers'), ('Shirts', 'Shirts'), ('T-Shirts', 'T-Shirts'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'))), ('Women', (('Saree', 'Saree'), ('Jeans', 'Jeans'), ('Tops', 'Tops'), ('Shirts', 'Shirts'), ('T-Shirts', 'T-Shirts'), ('Shoes', 'Shoes'), ('Accessories', 'Accessories'))), ('Kids', (('clothes for upto 2yrs kids', 'clothes for upto 2yrs kids'), ('clothes for upto 5yrs kids', 'clothes for upto 5yrs kids'), ('clothes for upto 10yrs kids', 'clothes for upto 10yrs kids'), ('clothes for upto 15yrs kids', 'clothes for upto 15yrs kids'), ('clothes for above 15yrs kids', 'clothes for above 15yrs kids'))), ('Computers', (('PC', 'PC'), ('Laptops', 'Laptops'), ('Accessories', 'Accessories'), ('Others', 'Others'))), ('Phones & Tablets', (('Bar Phones', 'Bar Phones'), ('Smartphones', 'Smartphones'), ('Smart Tablets', 'Smart Tablets'), ('Others', 'Others'))), ('Books', (('Literature', 'Literature'), ('Comics', 'Comics'), ('Story', 'Story'), ('Biography', 'Biography'), ('Educational', 'Educational'), ('Others', 'Others'))), ('Accessories', (('PC', 'PC'), ('Laptops', 'Laptops'), ('Phones', 'Phones'), ('Others', 'Others'))), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_choice',
            field=models.CharField(choices=[('None', 'None'), ('New', 'New Arrivals'), ('Trending', 'Trending'), ('Sales', 'Sales'), ('Regular', 'Regular Use'), ('Party', 'Party Wear'), ('Ethnic', 'Ethnic Wear')], max_length=20),
        ),
    ]
