# Generated by Django 3.1.7 on 2021-05-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_auto_20210515_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
