# Generated by Django 3.1.7 on 2021-05-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_auto_20210516_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='orderid',
            new_name='order',
        ),
    ]
