# Generated by Django 3.1.7 on 2021-05-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0020_auto_20210516_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='items',
        ),
    ]
