# Generated by Django 3.1.7 on 2021-05-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0021_remove_cartitems_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status1',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status4',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
