# Generated by Django 3.1.7 on 2021-05-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0022_auto_20210516_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
