# Generated by Django 3.1.7 on 2021-05-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0023_auto_20210516_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NA', '--Not-Available--'), ('Ordered', 'Ordered'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delievered', 'Delievered'), ('Cancelled', 'Cancelled')], default='NA', max_length=20),
        ),
    ]
