# Generated by Django 3.1.7 on 2021-05-18 14:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0025_auto_20210517_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_order', models.TextField(max_length=5000)),
                ('date_of_order', models.DateField(default=datetime.datetime(2021, 5, 18, 20, 28, 22, 463934))),
                ('is_complete', models.BooleanField(default=False)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('shipping_address', models.TextField(max_length=250)),
                ('phone', models.CharField(max_length=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
