# Generated by Django 3.1.7 on 2021-05-18 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0027_auto_20210518_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='date_of_order',
            field=models.DateField(default=datetime.datetime(2021, 5, 18, 15, 4, 9, 709223, tzinfo=utc)),
        ),
    ]
