# Generated by Django 3.1.7 on 2021-05-18 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0029_auto_20210518_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='date_of_order',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
