# Generated by Django 3.1.7 on 2021-05-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0031_auto_20210518_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
